# Generated by Django 2.2.4 on 2019-08-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='statement',
            new_name='complain',
        ),
    ]
