# Generated by Django 2.2.4 on 2019-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0004_complain_treated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='treated',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='Not Treated', max_length=50, null=True),
        ),
    ]
