# Generated by Django 2.2.4 on 2019-08-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0007_auto_20190826_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='treated',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, null=True),
        ),
    ]
